Repository lightstreams-network/lightchain, pull requests merged in 2019-02, with the labels that each got.

#69 [#68] Adding new ethereum account for testing proposes
  setup/sirius/database/keystore.go
  truffle/.env.sample
  truffle/truffle.js
Labels: improvement

#67 #61 Adds context to all logging across pkgs and corrects wording.
  cmd/lightchain/main.go
  consensus/abci.go
  consensus/api/api.go
  consensus/init.go
  consensus/node.go
  database/database.go
  database/events.go
  database/init.go
  database/node.go
  log/logger.go
  node/init.go
  node/node.go
Labels: improvement

#75 #74 Adds docs how to run Lightchain with RPC open.
  README.md
Labels: improvement

#83 78 prometheus intergration
  METRICS.md
  README.md
  cmd/lightchain/init.go
  cmd/lightchain/run.go
  consensus/abci.go
  consensus/config.go
  consensus/metrics/check_err_txs_total_metric.go
  consensus/metrics/check_txs_total_metric.go
  consensus/metrics/commit_block_total_metric.go
  consensus/metrics/commit_err_block_total_metric.go
  consensus/metrics/deliver_err_txs_total_metric.go
  consensus/metrics/deliver_txs_total_metric.go
  consensus/metrics/init.go
  consensus/node.go
  database/config.go
  database/database.go
  database/events.go
  database/metrics/broadcasted_tx_err_total_metric.go
  database/metrics/broadcasted_tx_total_metric.go
  database/metrics/chain_db_height_metric.go
  database/metrics/executed_txs_total.go
  database/metrics/init.go
  database/metrics/persisted_txs_total.go
  database/metrics/txs_cost_total.go
  database/metrics/txs_gas_total.go
  database/metrics/txs_size_total.go
  database/node.go
  docs/cmd/auto_generated/lightchain_init.md
  log/logger.go
  node/config.go
  node/node.go
  prometheus/collectors/eth_genesis_balance.go
  prometheus/collectors/eth_pending_block_transactions.go
  prometheus/collectors/eth_syncing.go
  prometheus/collectors/init.go
  prometheus/config.go
  prometheus/node.go
  prometheus/utils/ethereum.go
  scripts/run.sh
Labels: feature

#88 #79 Prevents lightchain node dir to be overwritten accidentally on init.
  cmd/lightchain/init.go
  database/node.go
  fs/dir.go
  node/init.go
  node/node.go
Labels: bug

#91 #70 Adding documentation to work around corrupted local state
  README.md
Labels: feature
