Repository lightstreams-network/lightchain, pull requests merged in 2019-05, with the labels that each got.

#143 #141 Implementing support for --wsapi and --wsorigins
  cmd/lightchain/ethereum_cli_ctx.go
  scripts/run.sh
Labels: feature

#147 Fixed dockerfile
  Dockerfile
Labels: bug

#167 #161 Upgrades Tendermint to version v0.31.5.
  Gopkg.lock
  Gopkg.toml
  cmd/lightchain/run.go
  cmd/lightchain/version.go
  database/database.go
  network/mainnet/consensus/genesis.go
  network/sirius/consensus/genesis.go
Labels: improvement
